# Generated by Django 5.2 on 2026-03-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_campo', models.CharField(max_length=50)),
                ('extensiones', models.CharField(default='.xlsx', max_length=50)),
                ('tipo', models.CharField(choices=[('CARGUE', 'Cargue por ejecucion'), ('FIJO', 'Insumo fijo')], default='CARGUE', max_length=10)),
                ('requerido', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTANDO', 'Ejecutando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('registros_nuevos', models.IntegerField(default=0)),
                ('registros_duplicados', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EncabezadoCXC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo_cxc', models.CharField(db_index=True, max_length=20)),
                ('consecutivo_original', models.CharField(blank=True, max_length=20)),
                ('tipo_documento', models.CharField(blank=True, max_length=10)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('primer_nombre', models.CharField(blank=True, max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100)),
                ('primer_apellido', models.CharField(blank=True, max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('total_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado_pago', models.CharField(blank=True, max_length=50)),
                ('estado_cxc', models.CharField(blank=True, max_length=50)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encabezados', to='etl.ejecucion')),
            ],
            options={
                'ordering': ['consecutivo_cxc'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCXC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_concepto', models.CharField(max_length=20)),
                ('centro_costo', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='etl.encabezadocxc')),
            ],
            options={
                'ordering': ['codigo_concepto'],
            },
        ),
        migrations.CreateModel(
            name='InsumoEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='insumos_ejecucion/')),
                ('nombre_original', models.CharField(max_length=200)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='etl.ejecucion')),
                ('insumo_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.insumodefinicion')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='muni.municipio')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'unique_together': {('municipio', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='insumodefinicion',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='etl.proceso'),
        ),
        migrations.AddField(
            model_name='encabezadocxc',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encabezados', to='etl.proceso'),
        ),
        migrations.AddField(
            model_name='ejecucion',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='etl.proceso'),
        ),
        migrations.AlterUniqueTogether(
            name='encabezadocxc',
            unique_together={('proceso', 'consecutivo_cxc')},
        ),
    ]
