# Generated by Django 5.2 on 2026-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecxc',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
