# Generated by Django 5.2 on 2026-09-25 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_alter_detallecxc_centro_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('procesos', models.CharField(blank=True, max_length=300)),
                ('destinatarios', models.TextField()),
                ('asunto', models.CharField(blank=True, max_length=250)),
                ('formato', models.CharField(max_length=10)),
                ('filtros', models.TextField(blank=True)),
                ('adjuntos', models.TextField(blank=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='etl.proceso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_exportacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
