# Generated by Django 5.2 on 2026-09-25 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_envio_exportacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saludo', models.CharField(default='Cordial saludo,', max_length=120)),
                ('mensaje', models.TextField(default='Se envía {adjuntos} en el sistema de información InOva del municipio de {municipio}, con corte al {fecha} a las {hora}.')),
                ('despedida', models.TextField(blank=True, default='Quedamos atentos a cualquier inquietud. Puedes responder este mensaje.')),
                ('firma_imagen', models.ImageField(blank=True, upload_to='firma/')),
                ('firma_texto', models.TextField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuración del correo de reportes',
            },
        ),
    ]
