# Generated by Django 5.2 on 2026-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_configuracion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucion',
            name='automatico',
            field=models.BooleanField(default=False),
        ),
    ]
