# Generated by Django 5.2 on 2026-03-31 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo_cxc', models.CharField(blank=True, max_length=10)),
                ('color_primario', models.CharField(default='#1B3A6B', max_length=7)),
                ('color_secundario', models.CharField(default='#2d6a9f', max_length=7)),
                ('color_texto_header', models.CharField(default='#ffffff', max_length=7)),
                ('fuente_principal', models.CharField(default='Montserrat, sans-serif', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('tiene_procesos', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('tipo_proceso', models.CharField(blank=True, max_length=30)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='muni.municipio')),
            ],
            options={
                'unique_together': {('municipio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='CIIUMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('INDUSTRIAL', 'Industrial'), ('COMERCIAL', 'Comercial'), ('SERVICIOS', 'Servicios')], max_length=15)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciiu', to='muni.municipio')),
            ],
            options={
                'unique_together': {('municipio', 'codigo')},
            },
        ),
    ]
