# Generated by Django 5.2 on 2026-09-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_temporal',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_temporal_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
