# Generated by Django 5.2 on 2026-09-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_password_temporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
